sudo: false

services: mongodb

language: ruby

before_install:
  - gem update bundler

cache: bundler

rvm:
  - 2.3.6

gemfile:
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile
  - gemfiles/mongoid-5.0.gemfile
  - gemfiles/mongoid-6.0.gemfile
  - gemfiles/mongoid-7.0.gemfile
  - gemfiles/mongoid-8.0.gemfile

matrix:
  include:
    - rvm: 2.3.6
      before_script:
        - bundle exec danger --verbose
  allow_failures:
    - env: MONGOID_VERSION=HEAD

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server

env:
  global:
    env:
      - RUBYOPT='-W0'
