sudo: false

services: mongodb

language: ruby

before_install:
  - gem update bundler

cache: bundler

rvm:
  - 2.4.1

gemfile:
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile
  - gemfiles/mongoid-5.0.gemfile
  - gemfiles/mongoid-6.0.gemfile

env:
  global:
    env:
      - RUBYOPT='-W0'
